name:                grids
version:             0.2.0.0
github:              "ChrisPenner/grids"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Arbitrary sized type-safe grids with useful combinators

dependencies:
- base >= 4.7 && < 5
- distributive
- vector
- adjunctions
- finite-typelits
- comonad
- singletons

library:
  source-dirs: src
  ghc-options: -fwarn-redundant-constraints
